###
GET http://localhost:5000/author-api/  



### post an article
POST http://localhost:5000/author-api/article
Content-Type: application/json

{
"author":"69b3c8c156b7a4d0e9428e96",
"title":"article on ai",
"category":"AI",
"content":"test my delete",
"comments":[]
}


###
GET  http://localhost:5000/author-api/articles

### update the article
PUT http://localhost:5000/author-api/data
Content-Type: application/json

{
    "articleId":"69b3ab82a23a25a5eea4822f",
    "title":"article on ai",
    "category":"AI",
    "content":"i updated this article"
}


###delete soft delete put is used to completely replace data and patch is for partially changing stuff like here ony one thing we will change
PATCH http://localhost:5000/author-api/articles
Content-Type: application/json

{
    "articleId":"69b40d453651e6bf2cdb0420",
    "isArticleActive":"false"
}
